---
- name: Change HTTPD Port
  hosts: web
  become: yes
  tasks:
    - name: Change the Listen port in the httpd configuration
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen 80'
        line: 'Listen 8080'
        backup: yes

    - name: Restart httpd service to apply changes
      service:
        name: httpd
        state: restarted
